import React, { useState, useEffect } from 'react';
import { collection, query, orderBy, limit, onSnapshot, getDocs } from 'firebase/firestore';
import { db } from '../firebase';
import { UserProfile, Signal } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Trophy, 
  MessageSquare, 
  Zap,
  Globe,
  Award,
  Flame,
  Star
} from 'lucide-react';

interface CommunityProps {
  userProfile: UserProfile;
  compact?: boolean;
}

export const Community: React.FC<CommunityProps> = ({ userProfile, compact = false }) => {
  const [globalSignals, setGlobalSignals] = useState<Signal[]>([]);
  const [leaderboard, setLeaderboard] = useState<any[]>([]);
  const [activeTab, setActiveTab] = useState<'feed' | 'leaderboard' | 'rooms'>('feed');

  useEffect(() => {
    // Global Signals Feed
    const q = query(
      collection(db, 'signals'),
      orderBy('created_at', 'desc'),
      limit(compact ? 5 : 20)
    );
    
    const unsubscribe = onSnapshot(q, (snap) => {
      setGlobalSignals(snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as Signal)));
    });

    return () => unsubscribe();
  }, [compact]);

  useEffect(() => {
    if (compact) return;
    // Leaderboard
    const fetchLeaderboard = async () => {
      const q = query(
        collection(db, 'users'),
        orderBy('win_rate', 'desc'),
        limit(10)
      );
      const snap = await getDocs(q);
      setLeaderboard(snap.docs.map(doc => ({ id: doc.id, ...doc.data() })));
    };
    
    fetchLeaderboard();
  }, [compact]);

  return (
    <div className={compact ? "space-y-4" : "space-y-8"}>
      {!compact && (
        <div className="flex gap-4 p-1 bg-white/5 rounded-xl border border-white/5 w-fit">
          <button
            onClick={() => setActiveTab('feed')}
            className={`px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center gap-2 ${activeTab === 'feed' ? 'bg-gold text-black' : 'text-white/40 hover:text-white/60'}`}
          >
            <Globe size={14} /> Global Feed
          </button>
          <button
            onClick={() => setActiveTab('leaderboard')}
            className={`px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center gap-2 ${activeTab === 'leaderboard' ? 'bg-gold text-black' : 'text-white/40 hover:text-white/60'}`}
          >
            <Trophy size={14} /> Oracle Leaderboard
          </button>
          <button
            onClick={() => setActiveTab('rooms')}
            className={`px-6 py-2 rounded-lg text-xs font-bold transition-all flex items-center gap-2 ${activeTab === 'rooms' ? 'bg-gold text-black' : 'text-white/40 hover:text-white/60'}`}
          >
            <MessageSquare size={14} /> Trading Rooms
          </button>
        </div>
      )}

      {activeTab === 'feed' ? (
        <div className={compact ? "space-y-4" : "grid grid-cols-1 lg:grid-cols-3 gap-8"}>
          <div className={compact ? "space-y-4" : "lg:col-span-2 space-y-4"}>
            <AnimatePresence mode="popLayout">
              {globalSignals.map((signal, i) => (
                <motion.div
                  key={signal.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className={`glass-card ${compact ? 'p-3' : 'p-4'} border-white/5 hover:border-gold/20 transition-all flex items-center justify-between gap-4`}
                >
                  <div className="flex items-center gap-4">
                    <div className={`${compact ? 'w-8 h-8' : 'w-12 h-12'} rounded-full bg-gold/10 flex items-center justify-center text-gold border border-gold/20`}>
                      <Zap size={compact ? 14 : 20} />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-sm">{signal.pair}</span>
                        <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${signal.tp1 > signal.entry ? 'bg-emerald-400/10 text-emerald-400' : 'bg-red-400/10 text-red-400'}`}>
                          {signal.tp1 > signal.entry ? 'BUY' : 'SELL'}
                        </span>
                      </div>
                      {!compact && (
                        <p className="text-[10px] text-white/40">
                          Generated by Oracle {signal.ai_bot} • {new Date(signal.created_at).toLocaleTimeString()}
                        </p>
                      )}
                    </div>
                  </div>
                  
                  <div className="text-right">
                    <div className="text-xs font-bold text-gold">{signal.confidence}%</div>
                    {!compact && <div className="text-[10px] text-white/40">RR: {signal.risk_reward}</div>}
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>

          {!compact && (
            <div className="space-y-6">
              <div className="glass-card p-6 space-y-4">
                <h3 className="font-display font-bold flex items-center gap-2">
                  <Flame className="text-orange-400" size={18} /> Hot Assets
                </h3>
                <div className="space-y-3">
                  {['Volatility 75', 'Crash 500', 'Boom 1000'].map((asset, i) => (
                    <div key={asset} className="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/5">
                      <span className="text-xs font-bold">{asset}</span>
                      <span className="text-[10px] text-emerald-400 font-bold">+{12 + i * 5}% Vol</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="glass-card p-6 space-y-4">
                <h3 className="font-display font-bold flex items-center gap-2">
                  <Star className="text-gold" size={18} /> Top Strategies
                </h3>
                <div className="space-y-3">
                  {['SMC / ICT Hybrid', 'MMM Power of 3', 'Supply/Demand Scalp'].map((strat, i) => (
                    <div key={strat} className="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/5">
                      <span className="text-xs font-bold">{strat}</span>
                      <span className="text-[10px] text-gold font-bold">{85 - i * 4}% Win Rate</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      ) : activeTab === 'leaderboard' ? (
        <div className="glass-card overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[600px]">
            <thead>
              <tr className="bg-white/5 border-b border-white/5">
                <th className="p-4 text-[10px] text-white/40 uppercase tracking-widest font-bold">Rank</th>
                <th className="p-4 text-[10px] text-white/40 uppercase tracking-widest font-bold">Oracle Trader</th>
                <th className="p-4 text-[10px] text-white/40 uppercase tracking-widest font-bold text-center">Win Rate</th>
                <th className="p-4 text-[10px] text-white/40 uppercase tracking-widest font-bold text-right">Total P/L</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {leaderboard.map((user, i) => (
                <tr key={user.id} className={`group hover:bg-white/5 transition-all ${user.id === userProfile.uid ? 'bg-gold/5' : ''}`}>
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <span className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold ${i < 3 ? 'bg-gold text-black' : 'bg-white/10 text-white/40'}`}>
                        {i + 1}
                      </span>
                      {i === 0 && <Award size={14} className="text-gold" />}
                    </div>
                  </td>
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-xs font-bold">
                        {user.username?.[0] || (user.email?.[0] || '?').toUpperCase()}
                      </div>
                      <div>
                        <p className="text-sm font-bold">{user.username || user.email.split('@')[0]}</p>
                        <p className="text-[10px] text-white/40 uppercase tracking-widest">{user.tier}</p>
                      </div>
                    </div>
                  </td>
                  <td className="p-4 text-center">
                    <span className="text-sm font-bold text-emerald-400">{user.win_rate?.toFixed(1) || 0}%</span>
                  </td>
                  <td className="p-4 text-right">
                    <span className={`text-sm font-mono font-bold ${user.total_pnl >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {user.total_pnl >= 0 ? '+' : ''}${user.total_pnl?.toFixed(2) || 0}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            { name: 'SMC Masters', members: 1250, active: 42, color: 'text-blue-400' },
            { name: 'ICT Inner Circle', members: 850, active: 28, color: 'text-purple-400' },
            { name: 'Volatility Scalpers', members: 2100, active: 156, color: 'text-emerald-400' },
            { name: 'Crash/Boom Hunters', members: 3400, active: 89, color: 'text-red-400' },
            { name: 'Fibonacci Wizards', members: 620, active: 15, color: 'text-gold' },
            { name: 'Price Action Elites', members: 1500, active: 64, color: 'text-zinc-400' }
          ].map((room, i) => (
            <motion.div
              key={room.name}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.1 }}
              className="glass-card p-6 space-y-6 group border-white/5 hover:border-gold/30 transition-all cursor-pointer"
            >
              <div className="flex items-start justify-between">
                <div className={`p-3 bg-white/5 rounded-xl border border-white/10 group-hover:bg-gold/10 transition-all ${room.color}`}>
                  <MessageSquare size={24} />
                </div>
                <div className="flex items-center gap-1 px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/20 rounded text-[10px] font-bold text-emerald-400">
                  <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse" />
                  {room.active} Live
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="text-lg font-bold text-white group-hover:text-gold transition-colors">{room.name}</h3>
                <p className="text-xs text-white/40">{room.members.toLocaleString()} Oracles Enrolled</p>
              </div>

              <button className="w-full py-3 bg-white/5 border border-white/10 rounded-xl text-xs font-bold text-white/60 group-hover:bg-gold group-hover:text-black group-hover:border-gold transition-all">
                Enter Room
              </button>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
};
